name: Update Articles

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml

      - name: Run Scraper
        run: python scraper.py

      - name: Check articles.json content
        run: cat articles.json || echo "articles.json not found or empty"

      - name: Check Git status
        run: git status

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          if [ -s articles.json ]; then
            git add articles.json
            git commit -m "Auto-updated articles" || echo "No changes to commit."
            git pull --rebase origin main
            git push origin main || echo "Failed to push changes."
          else
            echo "No changes to commit."
          fi
