name: Update Articles

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once daily at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add articles.json
          git commit -m "Auto-updated articles" || exit 0
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
